<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
<!--
комментарий
-->

<form>
    <input type="text" value="admin" readonly>
    <br>
    <input type="password" placeholder="enter the password">
    <br>
    someVal1<input type="radio" name="someVal">
    someVal2<input type="radio" name="someVal">
    <br>
    someVal3<input type="checkbox" name="someVal2">
    someVal4<input type="checkbox" name="someVal2">
    <br>
    <input type="color">
    <br>
    <b>Выберете дату</b>
    <input type="date">
    <input type="datetime-local">
    <input type="month">
    <br>
    <br>
    <p>введите email:
        <input type="email" value="email" aria-label="ddtlbnt ">
        <br>

        <input type="number" min="1" max="5" step="0.1">
        <br>
        1<input type="range" min="1" max="5">5
        <br>
        <input type="search">
        <br>
        <input type="tel">
        <br>
        <input type="time">
        <br>
        <input type="url">
        <br>
        <input type="week">
        <br>
        <input type="text" value="Пюре" list="dish">
        <br>
        user<input type="text" autocomplete="on" name="userfield">
        <br>
        <input type="file" multiple="">
        <br>
        <select multiple="">
            <option>Чебурашка</option>
            <option>Крокодил Гена</option>
            <option>Шапокляк</option>
            <option>Крыса Лариса</option>
        </select>
        <br>

        <input type="text" pattern="[0-4]{5,10}">
        <br>
        <input type="submit">
        <button disabled="">button</button>

        <datalist id="dish">
            <option value="Борщ" label="Борщ">
            </option><option value="Пельмени" label="Пельмени">
            </option><option value="Пюре" label="Пюре">
            </option><option value="Суп" label="Суп">
            </option><option value="Суши" label="Суши">
            </option></datalist>
</form>



</body>
</html>